library(ggplot2)
library(ggmap)
library(RColorBrewer)
library(png)

coords.data <- read.csv(file="./camps2016.csv")
min.longitude <- min(coords.data$DecimalLong)
min.latitude <- min(coords.data$DecimalLat)
max.longitude <- max(coords.data$DecimalLong)
max.latitude <- max(coords.data$DecimalLat)
map_bounds <- c(left = min.longitude-2, bottom = min.latitude-2, right = max.longitude+2, top = max.latitude+2)
coords.map <- get_stamenmap(map_bounds, zoom = 8, maptype = "terrain")
coords.map <- ggmap(coords.map, extent="device", legend="none")
coords.map <- coords.map + stat_density2d(data=coords.data,  aes(x=DecimalLong, y=DecimalLat, fill=..level.., alpha=..level..), geom="polygon", show.legend=FALSE)
coords.map <- coords.map +   scale_fill_gradientn(colours=rev(brewer.pal(8, "Spectral")))
ggsave(filename="./www/map2016.png")

coords.data <- read.csv(file="./camps2017.csv")
min.longitude <- min(coords.data$DecimalLong)
min.latitude <- min(coords.data$DecimalLat)
max.longitude <- max(coords.data$DecimalLong)
max.latitude <- max(coords.data$DecimalLat)
map_bounds <- c(left = min.longitude-2, bottom = min.latitude-2, right = max.longitude+2, top = max.latitude+2)
coords.map <- get_stamenmap(map_bounds, zoom = 8, maptype = "terrain")
coords.map <- ggmap(coords.map, extent="device", legend="none")
coords.map <- coords.map + stat_density2d(data=coords.data,  aes(x=DecimalLong, y=DecimalLat, fill=..level.., alpha=..level..), geom="polygon", show.legend=FALSE)
coords.map <- coords.map +   scale_fill_gradientn(colours=rev(brewer.pal(8, "Spectral")))
ggsave(filename="./www/map2017.png")

coords.data <- read.csv(file="./camps2018.csv")
min.longitude <- min(coords.data$DecimalLong)
min.latitude <- min(coords.data$DecimalLat)
max.longitude <- max(coords.data$DecimalLong)
max.latitude <- max(coords.data$DecimalLat)
map_bounds <- c(left = min.longitude-2, bottom = min.latitude-2, right = max.longitude+2, top = max.latitude+2)
coords.map <- get_stamenmap(map_bounds, zoom = 8, maptype = "terrain")
coords.map <- ggmap(coords.map, extent="device", legend="none")
coords.map <- coords.map + stat_density2d(data=coords.data,  aes(x=DecimalLong, y=DecimalLat, fill=..level.., alpha=..level..), geom="polygon", show.legend=FALSE)
coords.map <- coords.map +   scale_fill_gradientn(colours=rev(brewer.pal(8, "Spectral")))
ggsave(filename="./www/map2018.png")